/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_o2xfs_memory_impl_win32_Win32MemorySystem */

#ifndef _Included_at_o2xfs_memory_impl_win32_Win32MemorySystem
#define _Included_at_o2xfs_memory_impl_win32_Win32MemorySystem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_o2xfs_memory_impl_win32_Win32MemorySystem
 * Method:    allocate0
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_at_o2xfs_memory_impl_win32_Win32MemorySystem_allocate0
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     at_o2xfs_memory_impl_win32_Win32MemorySystem
 * Method:    free0
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_at_o2xfs_memory_impl_win32_Win32MemorySystem_free0
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     at_o2xfs_memory_impl_win32_Win32MemorySystem
 * Method:    read0
 * Signature: ([BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_at_o2xfs_memory_impl_win32_Win32MemorySystem_read0
  (JNIEnv *, jobject, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
